environment:

  matrix:
    # http://www.appveyor.com/docs/installed-software#python
    # pygraphviz cannot be installed via pip with Python 3.X (Linking errors)
    - PYTHON: "C:\\Python27"
#    - PYTHON: "C:\\Python33"
#    - PYTHON: "C:\\Python34"
#    - PYTHON: "C:\\Python35"
#    - PYTHON: "C:\\Python36"
#    - PYTHON: "C:\\Python27-x64"
#    - PYTHON: "C:\\Python33-x64"
#    - PYTHON: "C:\\Python34-x64"
#    - PYTHON: "C:\\Python35-x64"
#    - PYTHON: "C:\\Python36-x64"

install:
  - cinst graphviz
  - "%PYTHON%\\python.exe -m pip install pygraphviz \
  --install-option=\"--include-path=C:\\Program Files (x86)\\Graphviz2.38\\include\" \
  --install-option=\"--library-path=C:\\Program Files (x86)\\Graphviz2.38\\lib\\release\\lib\""
  - "%PYTHON%\\python.exe -m pip install -r requirements.txt"
  - "%PYTHON%\\python.exe -m pip install -r requirements_test.txt"

build: off

test_script:
  - "%PYTHON%\\python.exe -m nose --with-doctest"

#after_test:
#  # This step builds your wheels.
#  # Again, you only need build.cmd if you're building C extensions for
#  # 64-bit Python 3.3/3.4. And you need to use %PYTHON% to get the correct
#  # interpreter
#  - "%PYTHON%\\python.exe setup.py bdist_wheel"

#artifacts:
#  # bdist_wheel puts your built wheel in the dist directory
#  - path: dist\*

#on_success:
#  You can use this step to upload your artifacts to a public website.
#  See Appveyor's documentation for more details. Or you can simply
#  access your wheels from the Appveyor "artifacts" tab for your build.